/**
 * `just release <patch|minor|major>`: bump package.json, prepend a CHANGELOG.md entry built from the
 * commits since the last v*.*.* tag, commit both, and create an annotated tag vX.Y.Z.
 * It never pushes. `--dry-run` prints what it would do and changes nothing.
 * Needs Node 22.18+ (runs TypeScript directly).
 */
import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import {
  type BumpKind,
  GIT_LOG_FORMAT,
  bumpVersion,
  groupReleases,
  latestVersionTag,
  parseGitLog,
  renderReleaseMarkdown,
} from '../src/lib/releases.ts'

const git = (...args: string[]): string => execFileSync('git', args, { encoding: 'utf8' }).trim()
const fail = (message: string): never => {
  console.error(`release: ${message}`)
  process.exit(1)
}

const CHANGELOG_HEAD =
  '# Changelog\n\nGenerated by `just release`; the site also serves a live one at /CHANGELOG.md.\n\n'

const isBumpKind = (value: string | undefined): value is BumpKind =>
  value === 'patch' || value === 'minor' || value === 'major'

/** Work out the next version and its changelog entry from the commits since the last tag. */
const plan = (kind: BumpKind): { next: string; tag: string; entry: string } => {
  const lastTag = latestVersionTag(git('tag', '--list', 'v*').split('\n'))
  if (lastTag === null) {
    return fail('no v*.*.* tag exists yet; tag the 0.1.0 baseline first (see docs/releasing.md), then re-run')
  }
  const next = bumpVersion(lastTag, kind)
  const tag = `v${next}`
  if (git('tag', '--list', tag) !== '') return fail(`tag ${tag} already exists`)
  const commits = parseGitLog(git('log', '--topo-order', `--format=${GIT_LOG_FORMAT}`, `v${lastTag}..HEAD`))
  const unreleased = groupReleases(commits).find((release) => release.version === null)
  if (unreleased === undefined) return fail(`no changes since v${lastTag}`)
  const date = new Date().toISOString().slice(0, 10)
  return { next, tag, entry: renderReleaseMarkdown({ ...unreleased, version: next, tag, date }) }
}

/** Write package.json and CHANGELOG.md, commit them, and create the annotated tag. Never pushes. */
const apply = ({ next, tag, entry }: { next: string; tag: string; entry: string }): void => {
  const pkgText = readFileSync('package.json', 'utf8')
  writeFileSync('package.json', pkgText.replace(/("version":\s*")[^"]+(")/, `$1${next}$2`))
  const previous = existsSync('CHANGELOG.md') ? readFileSync('CHANGELOG.md', 'utf8') : CHANGELOG_HEAD
  const [head, ...rest] = previous.split(/(?=^## )/m)
  writeFileSync('CHANGELOG.md', `${head}${entry}\n${rest.join('')}`.trimEnd() + '\n')
  git('add', 'package.json', 'CHANGELOG.md')
  git('commit', '-m', `chore(release): ${tag}`)
  git('tag', '-a', tag, '-m', `Release ${tag}`)
  console.log(`Committed and tagged ${tag}. Nothing was pushed. To publish:\n  git push origin HEAD ${tag}`)
}

const main = (): void => {
  const [kind, flag] = process.argv.slice(2)
  if (!isBumpKind(kind)) return fail('usage: just release <patch|minor|major> [--dry-run]')
  const dryRun = flag === '--dry-run'
  if (!dryRun && git('status', '--porcelain') !== '') return fail('working tree is not clean; commit or stash first')
  const release = plan(kind)
  console.log(`Next version ${release.next}; tag ${release.tag} goes on the new release commit\n\n${release.entry}`)
  if (!dryRun) apply(release)
}

main()
